DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE OWNER CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE CAMPSITE CASCADE CONSTRAINTS;
DROP TABLE CAMPSITE_NOTICE CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE PROD_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE ZONE CASCADE CONSTRAINTS;
DROP TABLE PRD_PAYMENT CASCADE CONSTRAINTS;
DROP TABLE FAQ CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE PRD_REVIEW CASCADE CONSTRAINTS;
DROP TABLE PAY_TYPE CASCADE CONSTRAINTS;
DROP TABLE PRD_PAY_TYPE CASCADE CONSTRAINTS;
DROP TABLE CHATBOT CASCADE CONSTRAINTS;
DROP TABLE PROD_ORDER CASCADE CONSTRAINTS;
DROP TABLE RESERVATION CASCADE CONSTRAINTS;
DROP TABLE REFUND CASCADE CONSTRAINTS;
DROP TABLE OWNER_PROD_WISH CASCADE CONSTRAINTS;
DROP TABLE MEM_PROD_WISH CASCADE CONSTRAINTS;
DROP TABLE PRD_IMG CASCADE CONSTRAINTS;
DROP TABLE SEASON CASCADE CONSTRAINTS;
DROP TABLE PROD_ORDER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE RESERVATION_DETAIL CASCADE CONSTRAINTS;
DROP TABLE CAMP_IMG CASCADE CONSTRAINTS;
DROP TABLE ZONE_IMG CASCADE CONSTRAINTS;

--------------------DROP SEQ
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_PAYMENT_NO;
DROP SEQUENCE SEQ_OWNER_NO;
DROP SEQUENCE SEQ_ADMIN_NO;
DROP SEQUENCE SEQ_CAMPSITE_NO;
DROP SEQUENCE SEQ_CAMPSITE_NOTICE_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_PRODUCT_NO;
DROP SEQUENCE SEQ_PROD_CATEGORY_NO;
DROP SEQUENCE SEQ_EVENT_NO;
DROP SEQUENCE SEQ_ZONE_NO;
DROP SEQUENCE SEQ_PRD_PAYMENT_NO;
DROP SEQUENCE SEQ_FAQ_NO;
DROP SEQUENCE SEQ_REVIEW_NO;
DROP SEQUENCE SEQ_PRD_REVIEW_NO;
DROP SEQUENCE SEQ_PAY_TYPE_NO;
DROP SEQUENCE SEQ_PRD_PAY_TYPE_NO;
DROP SEQUENCE SEQ_CHATBOT_NO;
DROP SEQUENCE SEQ_PROD_ORDER_NO;
DROP SEQUENCE SEQ_RESERVATION_NO;
DROP SEQUENCE SEQ_REFUND_NO;
DROP SEQUENCE SEQ_OWNER_PROD_WISH_NO;
DROP SEQUENCE SEQ_MEM_PROD_WISH_NO;
DROP SEQUENCE SEQ_PRD_IMG_NO;
DROP SEQUENCE SEQ_SEASON_NO;
DROP SEQUENCE SEQ_PROD_ORDER_DETAIL_NO;
DROP SEQUENCE SEQ_CART_NO;
DROP SEQUENCE SEQ_RESERVATION_DETAIL_NO;
DROP SEQUENCE SEQ_CAMP_IMG_NO;
DROP SEQUENCE SEQ_ZONE_IMG_NO;



-------------SEQ CREATE
CREATE SEQUENCE SEQ_MEMBER_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_OWNER_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ADMIN_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CAMPSITE_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CAMPSITE_NOTICE_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_NOTICE_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PROD_CATEGORY_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_EVENT_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ZONE_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRD_PAYMENT_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_FAQ_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRD_REVIEW_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PAY_TYPE_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRD_PAY_TYPE_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CHATBOT_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PROD_ORDER_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_RESERVATION_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_REFUND_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_OWNER_PROD_WISH_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_MEM_PROD_WISH_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRD_IMG_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SEASON_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PROD_ORDER_DETAIL_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CART_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_RESERVATION_DETAIL_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CAMP_IMG_NO NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ZONE_IMG_NO NOCYCLE NOCACHE;

--------------TABLE CREATE-------------------------------
CREATE TABLE MEMBER (
	NO	NUMBER	CONSTRAINT PK_MEMBER_NO PRIMARY KEY,
	ID	VARCHAR2(100)	NOT NULL,
	PWD	VARCHAR2(100)	NOT NULL,
	NICK	VARCHAR2(100)	NOT NULL,
	ADDRESS	VARCHAR2(100)	NOT NULL,
	ZIP_CODE	CHAR(10)	NOT NULL,
	PHONE	CHAR(11)	NOT NULL,
	NAME	VARCHAR2(100)	NOT NULL,
	EMAIL	VARCHAR2(100)	NOT NULL,
	DEL_YN	CHAR(1)	DEFAULT 'N',
	CAMPING_COUPON	VARCHAR2(20)	NULL,
	PRODUCT_COUPON	VARCHAR2(20)	NULL
);

CREATE TABLE OWNER (
	NO	NUMBER	CONSTRAINT PK_OWNER_NO PRIMARY KEY,
	ID	VARCHAR2(100)	NOT NULL,
	PWD	VARCHAR2(100)	NOT NULL,
	NICK	VARCHAR2(100)	NOT NULL,
	NAME	VARCHAR2(100)	NOT NULL,
	PHONE	CHAR(11)	NOT NULL,
	EMAIL	VARCHAR2(100)	NOT NULL,
	ADDRESS	VARCHAR2(120)	NOT NULL,
	ZIP_CODE	VARCHAR2(10)	NOT NULL,
	BUSINESS_NUM	CHAR(10)	NOT NULL,
	JOIN_APPROVAL_YN	CHAR(1)	DEFAULT 'N'
);


CREATE TABLE ADMIN (
	NO	NUMBER	CONSTRAINT PK_ADMIN_NO PRIMARY KEY,
	ID	VARCHAR2(100)	NOT NULL,
	PWD	VARCHAR2(100)	NOT NULL,
	NICK	VARCHAR2(100)	NOT NULL
);



CREATE TABLE CAMPSITE (
	NO	NUMBER	CONSTRAINT PK_CAMPSITE_NO PRIMARY KEY,
	OWNER_NO	NUMBER	NOT NULL,
	NAME	VARCHAR2(100)	NOT NULL,
	ADDRESS	VARCHAR2(100)	NOT NULL,
	TEL	VARCHAR2(100)	NOT NULL,
	INTRODUCTION	VARCHAR2(4000)	NOT NULL,
	BASIC_INFO	VARCHAR2(1000)	NOT NULL,
	ZONE_LAYOUT_IMG	VARCHAR2(255)	NOT NULL,
	LONGITUDE	NUMBER	NULL,
	LATITUDE	NUMBER	NULL,
	DEL_YN	CHAR(1)	DEFAULT 'N',
	AREA	VARCHAR2(100)	NOT NULL,
	HOLI_DAY	DATE	NULL,
	BLIND_CAMP	CHAR(1)	DEFAULT 'N',
	CAMPSITE_CATEGORY	VARCHAR(100)	NOT NULL,
	SINK	CHAR(1)	DEFAULT 'N',
	WIFI	CHAR(1)	DEFAULT 'N',
	MARKET	CHAR(1)	DEFAULT 'N',
	SHOWER	CHAR(1)	DEFAULT 'N',
	TOILET	CHAR(1)	DEFAULT 'N',
	ELECTRIC_STATION	CHAR(1)	DEFAULT 'N',
	BBQ	CHAR(1)		DEFAULT 'N',
	CAFE	CHAR(1)		DEFAULT 'N',
	POOL	CHAR(1)		DEFAULT 'N',
	ACTIVITY	CHAR(1)		DEFAULT 'N',
	PLAYGROUND	CHAR(1)		DEFAULT 'N',
	PET	CHAR(1)		DEFAULT 'N',
	TRAILER	CHAR(1)		DEFAULT 'N',
	CARAVAN	CHAR(1)		DEFAULT 'N',
	TRACKING	CHAR(1)		DEFAULT 'N',
	TRAMPOLINE	CHAR(1)		DEFAULT 'N',
	SLEIGH	CHAR(1)		DEFAULT 'N',
	CAMPING_TOOL	CHAR(1)		DEFAULT 'N',
	WATER_PLAY	CHAR(1)		DEFAULT 'N',
	FISHING	CHAR(1)		DEFAULT 'N',
	WATER_ACTIVITY	CHAR(1)		DEFAULT 'N',
	MTB	CHAR(1)		DEFAULT 'N',
	HIKING	CHAR(1)		DEFAULT 'N',
	GOLF	CHAR(1)		DEFAULT 'N',
	BEACH	CHAR(1)		DEFAULT 'N',
	SKI	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE CAMPSITE_NOTICE (
	NO	NUMBER	CONSTRAINT PK_CAMPSITE_NOTICE_NO PRIMARY KEY,
	CAMPSITE_NO	NUMBER	NOT NULL,
	TITLE	VARCHAR2(1000)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	UPLOAD_DATE	TIMESTAMP	DEFAULT SYSDATE,
	DEL_YN	CHAR(1)		DEFAULT 'N',
	MODIFY_DATE	TIMESTAMP	NULL,
	HIT	NUMBER		DEFAULT 0
);



CREATE TABLE NOTICE (
	NO	NUMBER	CONSTRAINT PK_NOTICE_NO PRIMARY KEY,
	WRITER	NUMBER	NOT NULL,
	TITLE	VARCHAR2(1000)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	HIT	NUMBER		DEFAULT 0,
	CREATE_DATE	TIMESTAMP		DEFAULT SYSDATE,
	MODIFY_DATE	TIMESTAMP	NULL,
	DEL_YN	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE PRODUCT (
	NO	NUMBER	CONSTRAINT PK_PRODUCT_NO PRIMARY KEY,
	CATEGORY_NO	NUMBER	NOT NULL,
	NAME	VARCHAR2(100)	NOT NULL,
	PRICE	NUMBER	NOT NULL,
	PROD_EXPLAIN	VARCHAR2(4000)	NOT NULL,
	STOCK	NUMBER	NOT NULL,
	CREATE_DATE	TIMESTAMP		DEFAULT SYSDATE,
	DEL_YN	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE PROD_CATEGORY (
	NO	NUMBER	CONSTRAINT PK_PROD_CATEGORY_NO PRIMARY KEY,
	TYPE	VARCHAR2(100)	NOT NULL
);



CREATE TABLE EVENT (
	NO	NUMBER	CONSTRAINT PK_EVENT_NO PRIMARY KEY,
	WRITER	NUMBER	NOT NULL,
	TITLE	VARCHAR2(1000)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	CONTENT_IMG	VARCHAR2(255)	NOT NULL,
	HIT	NUMBER		DEFAULT 0,
	CREATE_DATE	TIMESTAMP		DEFAULT SYSDATE,
	MODIFY_DATE	TIMESTAMP	NULL,
	DEL_YN	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE ZONE (
	NO	NUMBER	CONSTRAINT PK_ZONE_NO PRIMARY KEY,
	CAMPSITE_NO	NUMBER	NOT NULL,
	SEASON_NO	NUMBER	NOT NULL,
	MAX_PEOPLE	NUMBER	NULL,
	PRICE	NUMBER	NULL,
	ZONE_CATEGORY	VARCHAR2(100)	NOT NULL
);



CREATE TABLE PAYMENT (
	NO	NUMBER	CONSTRAINT PK_PAYMENT_NO PRIMARY KEY,
	PAY_TYPE	NUMBER 	NOT NULL,
	BOOK_NO	NUMBER	NOT NULL,
	PAY_YN	CHAR(1)		DEFAULT 'N',
	PAY_DATE	TIMESTAMP		DEFAULT SYSDATE
);



CREATE TABLE PRD_PAYMENT (
	NO	NUMBER	CONSTRAINT PK_PRD_PAYMENT_NO PRIMARY KEY,
	PRD_PAY_TYPE_NO	NUMBER	NOT NULL,
	PROD_ORDER_NO	NUMBER	NOT NULL,
	PAYED_DATE	TIMESTAMP		DEFAULT SYSDATE,
	PAY_YN	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE FAQ (
	NO	NUMBER	CONSTRAINT PK_FAQ_NO PRIMARY KEY,
	WRITER	NUMBER	NOT NULL,
	TITLE	VARCHAR2(1000)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	HIT	NUMBER		DEFAULT 0,
	CREATE_DATE	TIMESTAMP		DEFAULT SYSDATE,
	MODIFY_DATE	TIMESTAMP	NULL,
	DEL_YN	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE REVIEW (
	NO	NUMBER	CONSTRAINT PK_REVIEW_NO PRIMARY KEY,
	PAYMENT_NO	NUMBER	NOT NULL,
	TITLE	VARCHAR2(1000)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	STAR_POINT	NUMBER	NOT NULL,
	CREATE_DATE	TIMESTAMP		DEFAULT SYSDATE,
	MODIFY_DATE	TIMESTAMP	NULL,
	DEL_YN	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE PRD_REVIEW (
	NO	NUMBER	CONSTRAINT PK_PRD_REVIEW_NO PRIMARY KEY,
	REVIEWER_NO	NUMBER	NOT NULL,
	TITLE	VARCHAR2(1000)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	STAR_POINT	NUMBER	NOT NULL,
	CREATE_DATE	TIMESTAMP		DEFAULT SYSDATE,
	MODIFY_DATE	TIMESTAMP	NULL,
	DEL_YN	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE PAY_TYPE (
	NO	NUMBER	CONSTRAINT PK_PAY_TYPE_NO PRIMARY KEY,
	TYPE	VARCHAR2(100)	NOT NULL
);



CREATE TABLE PRD_PAY_TYPE (
	NO	NUMBER	CONSTRAINT PK_PRD_PAY_TYPE_NO PRIMARY KEY,
	TYPE	VARCHAR2(100)	NOT NULL
);



CREATE TABLE CHATBOT (
	NO	NUMBER	CONSTRAINT PK_CHATBOT_NO PRIMARY KEY,
	QUESTION	VARCHAR2(1000)	NOT NULL,
	ANSWER	VARCHAR2(4000)	NOT NULL
);



CREATE TABLE PROD_ORDER (
	NO	NUMBER	CONSTRAINT PK_PROD_ORDER_NO PRIMARY KEY,
	MEMBER_NO	NUMBER	NOT NULL,
	PROD_ORDER_DATE	TIMESTAMP	DEFAULT SYSDATE,
	PROD_ORDER_YN	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE RESERVATION (
	NO	NUMBER	CONSTRAINT PK_RESERVATION_NO PRIMARY KEY,
	ZONE_NO	NUMBER	NOT NULL,
	MEM_NO	NUMBER	NOT NULL,
	BOOK_DATE	TIMESTAMP		DEFAULT SYSDATE,
	START_DATE	DATE	NOT NULL,
	END_DATE	DATE	NOT NULL,
	COUNT	NUMBER	NOT NULL
);



CREATE TABLE REFUND (
	NO	NUMBER	CONSTRAINT PK_REFUND_NO PRIMARY KEY,
	REFUND_PERIOD	VARCHAR2(100)	NOT NULL,
	REFUND_PERCENT	NUMBER	NOT NULL
);



CREATE TABLE OWNER_PROD_WISH (
	NO	NUMBER	CONSTRAINT PK_OWNER_PROD_WISH_NO PRIMARY KEY,
	WRITER_NO	NUMBER	NOT NULL,
	ADMIN_NO	NUMBER	NOT NULL,
	TITLE	VARCHAR2(1000)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	ANSWER	VARCHAR2(4000)	NULL,
	HIT	NUMBER		DEFAULT 0,
	CREATE_DATE	TIMESTAMP		DEFAULT SYSDATE,
	DEL_YN	CHAR(1)		DEFAULT 'N',
	ANSWER_DATE	TIMESTAMP	DEFAULT SYSDATE
);



CREATE TABLE MEM_PROD_WISH (
	NO	NUMBER	CONSTRAINT PK_MEM_PROD_WISH_NO PRIMARY KEY,
	WRITER_NO	NUMBER	NOT NULL,
	ADMIN_NO	NUMBER	NOT NULL,
	TITLE	VARCHAR2(1000)	NOT NULL,
	CONTENT	VARCHAR2(4000)	NOT NULL,
	ANSWER	VARCHAR2(4000)	NULL,
	HIT	NUMBER		DEFAULT 0,
	CREATE_DATE	TIMESTAMP		DEFAULT SYSDATE,
	DEL_YN	CHAR(1)		DEFAULT 'N',
	ANSWER_DATE	TIMESTAMP	DEFAULT SYSDATE
);



CREATE TABLE PRD_IMG (
	NO	NUMBER	CONSTRAINT PK_PRD_IMG_NO PRIMARY KEY,
	PRD_NO	NUMBER	NOT NULL,
	DEL_YN	CHAR(1)		DEFAULT 'N',
	PHOTO	VARCHAR2(225)	NULL
);



CREATE TABLE SEASON (
	NO	NUMBER	CONSTRAINT PK_SEASON_NO PRIMARY KEY,
	TYPE	VARCHAR2(100)	NOT NULL,
	START_DATE	DATE	NOT NULL,
	END_DATE	DATE	NOT NULL
);



CREATE TABLE PROD_ORDER_DETAIL (
	NO	NUMBER	CONSTRAINT PK_PROD_ORDER_DETAIL_NO PRIMARY KEY,
	PROD_ORDER_NO	NUMBER	NOT NULL,
	PROD_NO	NUMBER	NOT NULL,
	QUANTITY	NUMBER	NOT NULL,
	TOTAL_PRICE	NUMBER	NOT NULL
);



CREATE TABLE CART (
	Key	NUMBER	CONSTRAINT PK_CART_NO PRIMARY KEY,
	MEMBER_NO	NUMBER	NOT NULL,
	PROD_NO	NUMBER	NOT NULL,
	PROD_CUT	NUMBER	NOT NULL
);



CREATE TABLE RESERVATION_DETAIL (
	Key	NUMBER	CONSTRAINT PK_RESERVATION_DETAIL_NO PRIMARY KEY,
	PAY_NO	NUMBER	NOT NULL,
	RESERVATION_NO	NUMBER	NOT NULL,
	CANCEL_YN	CHAR(1)		DEFAULT 'N'
);



CREATE TABLE CAMP_IMG (
	Key	NUMBER	CONSTRAINT PK_CAMP_IMG_NO PRIMARY KEY,
	NO	NUMBER	NOT NULL,
	FILE_PATH	VARCHAR2(1000)	NOT NULL,
	DEL_YN	CHAR(1)		DEFAULT 'N',
	CREATE_DATE	DATE		DEFAULT SYSDATE
);



CREATE TABLE ZONE_IMG (
	Key	NUMBER	CONSTRAINT PK_ZONE_IMG_NO PRIMARY KEY,
	CAMPINGZONE_NO	NUMBER	NOT NULL,
	FILE_PATH	VARCHAR2(1000)	NOT NULL,
	DEL_YN	CHAR(1)		DEFAULT 'N',
	CREATE_DATE	DATE		DEFAULT SYSDATE
);



ALTER TABLE CAMPSITE ADD CONSTRAINT FK_OWNER_TO_CAMPSITE_1 FOREIGN KEY (
	OWNER_NO
)
REFERENCES OWNER (
	NO
);

ALTER TABLE CAMPSITE_NOTICE ADD CONSTRAINT FK_CAMPSITE_TO_CAMPSITE_NOTICE_1 FOREIGN KEY (
	CAMPSITE_NO
)
REFERENCES CAMPSITE (
	NO
);

ALTER TABLE NOTICE ADD CONSTRAINT FK_ADMIN_TO_NOTICE_1 FOREIGN KEY (
	WRITER
)
REFERENCES ADMIN (
	NO
);

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PROD_CATEGORY_TO_PRODUCT_1 FOREIGN KEY (
	CATEGORY_NO
)
REFERENCES PROD_CATEGORY (
	NO
);

ALTER TABLE EVENT ADD CONSTRAINT FK_ADMIN_TO_EVENT_1 FOREIGN KEY (
	WRITER
)
REFERENCES ADMIN (
	NO
);

ALTER TABLE ZONE ADD CONSTRAINT FK_CAMPSITE_TO_ZONE_1 FOREIGN KEY (
	CAMPSITE_NO
)
REFERENCES CAMPSITE (
	NO
);

ALTER TABLE ZONE ADD CONSTRAINT FK_SEASON_TO_ZONE_1 FOREIGN KEY (
	SEASON_NO
)
REFERENCES SEASON (
	NO
);

ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAY_TYPE_TO_PAYMENT_1 FOREIGN KEY (
	PAY_TYPE
)
REFERENCES PAY_TYPE (
	NO
);

ALTER TABLE PAYMENT ADD CONSTRAINT FK_RESERVATION_TO_PAYMENT_1 FOREIGN KEY (
	BOOK_NO
)
REFERENCES RESERVATION (
	NO
);

ALTER TABLE PRD_PAYMENT ADD CONSTRAINT FK_PRD_PAY_TYPE_TO_PRD_PAYMENT_1 FOREIGN KEY (
	PRD_PAY_TYPE_NO
)
REFERENCES PRD_PAY_TYPE (
	NO
);

ALTER TABLE PRD_PAYMENT ADD CONSTRAINT FK_PROD_ORDER_TO_PRD_PAYMENT_1 FOREIGN KEY (
	PROD_ORDER_NO
)
REFERENCES PROD_ORDER (
	NO
);

ALTER TABLE FAQ ADD CONSTRAINT FK_ADMIN_TO_FAQ_1 FOREIGN KEY (
	WRITER
)
REFERENCES ADMIN (
	NO
);

ALTER TABLE REVIEW ADD CONSTRAINT FK_PAYMENT_TO_REVIEW_1 FOREIGN KEY (
	PAYMENT_NO
)
REFERENCES PAYMENT (
	NO
);

ALTER TABLE PRD_REVIEW ADD CONSTRAINT FK_PRD_PAYMENT_TO_PRD_REVIEW_1 FOREIGN KEY (
	REVIEWER_NO
)
REFERENCES PRD_PAYMENT (
	NO
);

ALTER TABLE PROD_ORDER ADD CONSTRAINT FK_MEMBER_TO_PROD_ORDER_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	NO
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_ZONE_TO_RESERVATION_1 FOREIGN KEY (
	ZONE_NO
)
REFERENCES ZONE (
	NO
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_MEMBER_TO_RESERVATION_1 FOREIGN KEY (
	MEM_NO
)
REFERENCES MEMBER (
	NO
);

ALTER TABLE OWNER_PROD_WISH ADD CONSTRAINT FK_OWNER_TO_OWNER_PROD_WISH_1 FOREIGN KEY (
	WRITER_NO
)
REFERENCES OWNER (
	NO
);

ALTER TABLE OWNER_PROD_WISH ADD CONSTRAINT FK_ADMIN_TO_OWNER_PROD_WISH_1 FOREIGN KEY (
	ADMIN_NO
)
REFERENCES ADMIN (
	NO
);

ALTER TABLE MEM_PROD_WISH ADD CONSTRAINT FK_MEMBER_TO_MEM_PROD_WISH_1 FOREIGN KEY (
	WRITER_NO
)
REFERENCES MEMBER (
	NO
);

ALTER TABLE MEM_PROD_WISH ADD CONSTRAINT FK_ADMIN_TO_MEM_PROD_WISH_1 FOREIGN KEY (
	ADMIN_NO
)
REFERENCES ADMIN (
	NO
);

ALTER TABLE PRD_IMG ADD CONSTRAINT FK_PRODUCT_TO_PRD_IMG_1 FOREIGN KEY (
	PRD_NO
)
REFERENCES PRODUCT (
	NO
);

ALTER TABLE PROD_ORDER_DETAIL ADD CONSTRAINT FK_PROD_ORDER_TO_PROD_ORDER_DETAIL_1 FOREIGN KEY (
	PROD_ORDER_NO
)
REFERENCES PROD_ORDER (
	NO
);

ALTER TABLE PROD_ORDER_DETAIL ADD CONSTRAINT FK_PRODUCT_TO_PROD_ORDER_DETAIL_1 FOREIGN KEY (
	PROD_NO
)
REFERENCES PRODUCT (
	NO
);

ALTER TABLE CART ADD CONSTRAINT FK_MEMBER_TO_CART_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	NO
);

ALTER TABLE CART ADD CONSTRAINT FK_PRODUCT_TO_CART_1 FOREIGN KEY (
	PROD_NO
)
REFERENCES PRODUCT (
	NO
);

ALTER TABLE RESERVATION_DETAIL ADD CONSTRAINT FK_PAYMENT_TO_RESERVATION_DETAIL_1 FOREIGN KEY (
	PAY_NO
)
REFERENCES PAYMENT (
	NO
);

ALTER TABLE RESERVATION_DETAIL ADD CONSTRAINT FK_RESERVATION_TO_RESERVATION_DETAIL_1 FOREIGN KEY (
	RESERVATION_NO
)
REFERENCES RESERVATION (
	NO
);

ALTER TABLE CAMP_IMG ADD CONSTRAINT FK_CAMPSITE_TO_CAMP_IMG_1 FOREIGN KEY (
	NO
)
REFERENCES CAMPSITE (
	NO
);

ALTER TABLE ZONE_IMG ADD CONSTRAINT FK_ZONE_TO_ZONE_IMG_1 FOREIGN KEY (
	CAMPINGZONE_NO
)
REFERENCES ZONE (
	NO
);

